#!/bin/sh

PREREQ=""
DESCRIPTION="Enabling detection of crashes..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

if [ -e /root/etc/default/apport ]; then
    sed -i 's/enabled=0/enabled=1/' /root/etc/default/apport
fi

log_end_msg
