#!/bin/sh

PREREQ=""
DESCRIPTION="Disabling jockey driver check..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

rm -f /root/etc/xdg/autostart/jockey*.desktop

log_end_msg
