#! /bin/sh

PREREQ=""
DESCRIPTION="Adding APT-CDROM source..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

chroot /root apt-cdrom -m add
