#!/bin/sh
# Fix for LP#150188

PREREQ=""
DESCRIPTION="Possibly disabling update-initramfs (useless on a live CD)..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

chroot /root dpkg-divert --add --rename --quiet \
        /usr/sbin/update-initramfs
# Running off a USB disk or other writable media.
if [ -w /root/cdrom ] && \
   ! grep -q '^[^ ]* /root/cdrom [^ ]* [^ ]*\<ro\>' /proc/mounts; then
	cat > /root/usr/sbin/update-initramfs <<'EOF'
#! /bin/sh
update-initramfs.distrib "$@"
cp /initrd.img /cdrom/casper/initrd.gz
cp /vmlinuz /cdrom/casper/vmlinuz
exit 0
EOF
else
	cat > /root/usr/sbin/update-initramfs <<EOF
#! /bin/sh
echo "update-initramfs is disabled since running on read-only media"
exit 0
EOF
fi

chmod 755 /root/usr/sbin/update-initramfs

log_end_msg
