#!/bin/sh

PREREQ=""
DESCRIPTION="Disabling gdm guest session functionality..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

chroot /root rm -rf /usr/share/gdm/guest-session

log_end_msg
